# MySQL Variables

mysql_database_name: "serpent_surge_db"      # Name of the MySQL database
mysql_user: "serpent_user"                    # MySQL username that will be created
mysql_password: "{{ lookup('password', '/dev/null length=15 chars=ascii_letters') }}"  # Automatically generate a secure password for the MySQL user
mysql_root_password: "root_password"         # Root password for MySQL (for administrative tasks, if required)

# Paths
mysql_user_home: "/home/{{ mysql_user }}"    # Home directory of the MySQL user (serpent_user)
mycnf_path: "{{ mysql_user_home }}/.my.cnf"  # Path to store .my.cnf for the created MySQL user
