version: "3.9"

services:
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - serpent_network

  backend:
    image: backend-image:latest
    build:
      context: ${BACKEND_DIR}
    environment:
      - MYSQL_HOST=devops_at-_nix-mysql-1
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_USER_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_PORT=3306
    depends_on:
      - mysql
    ports:
      - "3000:3000"
    networks:
      - serpent_network

  frontend:
    image: frontend-image:latest
    build:
      context: ${FRONTEND_DIR}
    ports:
      - "8080:80"
    networks:
      - serpent_network

volumes:
  mysql_data:

networks:
  serpent_network:
    driver: bridge

