version: '3.8'

services:
  backend:
    build:
      context: /var/git/git_task/DevOps_at-_NIX/application
      dockerfile: backend/Dockerfile
    depends_on:
      mysql:
        condition: service_healthy  # Change to service_healthy for better handling of readiness
    environment:
      MYSQL_CNF_PATH: /home/serpent_user/.my.cnf
      MYSQL_DATABASE: serpent_surge_db
      MYSQL_HOST: mysql
    networks:
      serpent_network: null
    ports:
      - published: 3000
        target: 3000
    user: 1001:1001
    volumes:
      - /home/serpent_user/.my.cnf:/home/serpent_user/.my.cnf:ro  # Mount .my.cnf here

  frontend:
    build:
      context: /var/git/git_task/DevOps_at-_NIX/application
      dockerfile: frontend/Dockerfile
    depends_on:
      backend:
        condition: service_started
    networks:
      serpent_network: null
    ports:
      - published: 8080
        target: 80

  mysql:
    image: mysql:8.0
    networks:
      serpent_network: null
    volumes:
      - mysql_data:/var/lib/mysql:rw
      - /home/serpent_user/.my.cnf:/etc/mysql/my.cnf:ro  # Mount .my.cnf in MySQL container (read-only)

volumes:
  mysql_data: {}

networks:
  serpent_network:
    driver: bridge

