version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: serpent_surge_db
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - serpent_network

  backend:
    build:
      context: ./application  # Path to the application directory
      dockerfile: backend/Dockerfile  # Dockerfile for backend (Node.js Alpine)
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_DATABASE: serpent_surge_db
      MYSQL_CNF_PATH: /home/serpent_user/.my.cnf  # Path to .my.cnf file for serpent_user
    volumes:
      - /home/serpent_user/.my.cnf:/home/serpent_user/.my.cnf:ro  # Mount the .my.cnf file
    networks:
      - serpent_network
    ports:
      - "3000:3000"  # Backend is exposed on port 3000
   

  frontend:
    build:
      context: ./application  # Path to the application directory
      dockerfile: frontend/Dockerfile  # Dockerfile for frontend (Nginx + static files)
    depends_on:
      - backend
    networks:
      - serpent_network
    ports:
      - "8080:80"  # Frontend is exposed on port 8080, Nginx listens on port 80

volumes:
  mysql_data:   # Volume for persistent MySQL data

networks:
  serpent_network:   # Custom network for seamless service communication
    driver: bridge

