# tasks/main.yml in common_prereq role
---
- name: Ensure Python 3 is installed
  apt:
    name: python3
    state: present
    update_cache: yes

- name: Install pip
  apt:
    name: python3-pip
    state: present

- name: Install PyMySQL via apt
  apt:
    name: python3-pymysql
    state: present
  become: yes

- name: Ensure ACL package is installed
  package:
    name: acl
    state: present
  become: yes

