---
- name: Complete server setup using Docker
  hosts: all
  become: true
  vars_files: 
    - /var/git/git_task/DevOps_at-_NIX/ansible/roles/nginx/templates/vars.yml
    - /var/git/git_task/DevOps_at-_NIX/ansible/roles/mysql/vars/mysql_vars.yml 
  roles:
    - common_prereq
    - mysql
    - nginx
    - docker
