---
- name: Complete server setup using Docker
  hosts: all
  become: true
  vars_files: 
    - /etc/ansible/roles/nginx/templates/vars.yml
    - /etc/ansible/roles/mysql/vars/mysql_vars.yml 
  roles:
    - common_prereq
    - mysql
    - docker
    - nginx
