---

- name: Install MySQL Server
  apt:
    name: mysql-server
    state: present
  become: yes

- name: Configure MySQL to listen on all interfaces
  lineinfile:
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    regexp: '^bind-address'
    line: 'bind-address = 0.0.0.0'
  notify: Restart MySQL

- name: Start and enable MySQL service
  service:
    name: mysql
    state: started
    enabled: yes
  become: yes

- name: Ensure MySQL data directory ownership is correct
  file:
    path: /var/lib/mysql
    owner: mysql
    group: mysql
    recurse: yes
  become: yes

- name: Create MySQL Database
  mysql_db:
    name: "{{ mysql_database_name }}"
    state: present
    login_user: "{{ mysql_root_user }}"
    login_password: "{{ mysql_root_password }}"
  become: yes

- name: Create MySQL User
  mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ mysql_user_password }}"
    state: present
    login_user: "{{ mysql_root_user }}"
    login_password: "{{ mysql_root_password }}"
  become: yes

- name: Grant ALL privileges to the MySQL User on the database
  mysql_user:
    name: "{{ mysql_user }}"
    priv: "{{ mysql_database_name }}.*:ALL"
    state: present
    login_user: "{{ mysql_root_user }}"
    login_password: "{{ mysql_root_password }}"
  become: yes

- name: Create score table in the database
  mysql_query:
    query: |
      CREATE TABLE IF NOT EXISTS score (
        id INT PRIMARY KEY AUTO_INCREMENT,
        name TEXT,
        score INT,
        difficulty INT
      );
    login_user: "{{ mysql_user }}"
    login_password: "{{ mysql_user_password }}"
    login_db: "{{ mysql_database_name }}"
  
  become: yes
  delegate_to: localhost
